### ISSUE TITLE
Make it easier to set all parameters

### ISSUE THREAD

**Issue by heidmic** [heidmic/suprb#146]
Currently, you need to generate objects from deep within suprb to set some parameters. That is fine when interacting with suprb-experimentation but should be different for a standalone solution

**Comment by dpaetzel** [comment]
Yes! More flat parameters would definitely help with things like parameter tuning. E.g. I would like to be able to do

```
SupRB(rd_delay=10, sc_selection_type="Tournament", sc_selection_params={"k" : 2})
```

or even

```
SupRB(rd_delay=10, sc_selection_type="Tournament", sc_selection_param_k=2)
```

I guess, however, that both forms would require some minimal form of parameter validation, though, especially since some parameters are conditional.

This should probably (in my opinion) be optional, though; if someone *wants* to create objects and supply them as arguments, they should be able to do so as well.

Note that there is something faintly similar to this parameter name chaining (using `sklearn.utils.Bunch` etc.) in *suprb-experimentation* already which could maybe be adjusted and incorporated into *suprb* itself.
